### ISSUE TITLE
Running Updater.py gives exception

### ISSUE THREAD

**Issue by SCP002** [DUOLabs333/Photopea-Offline#12]
On windows 11, running Updater.py crashes with:
```
...
www.photopea.com/code/pp/pp1733777484.js: 2.40MB [00:01, 1.96MB/s]
Traceback (most recent call last):
  File "D:\Downloads\Photopea\Updater.py", line 176, in <module>
    find_and_replace(PP,'"\'$!|"))','"\'$!|"))||true')
  File "D:\Downloads\Photopea\Updater.py", line 170, in find_and_replace
    file1=pp.read()
          ^^^^^^^^^
  File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 19146: character maps to <undefined>
```

**Comment by SCP002** [comment]
It can be fixed by changing `find_and_replace` function to:
```py
def find_and_replace(file,find,replace):
    with open(os.path.join(root,file),'r',encoding='utf-8') as pp:
        file1=pp.read()
    file1=file1.replace(find,replace)
    with open(os.path.join(root,file),'w',encoding='utf-8') as pp:
        pp.write(file1)
```

**Comment by DUOLabs333** [comment]
Interesting that this problem shows up again on Windows --- thanks for pointing it out. I'll see if I can set the default codec when reading and writing files to UTF-8.

**Comment by DUOLabs333** [comment]
It turns out there's no easy way to fix this without potentially breaking something else, so I'll just set UTF-8 for all `open` calls (though apparently this error will go away on its own in Python 3.15, as PEP 686 got accepted).

**Comment by SCP002** [comment]
Forgot to mention, I've tried it with embeddable package of python version 3.12.8

**Comment by DUOLabs333** [comment]
This should be fixed now.

**Comment by SCP002** [comment]
Unfortunately, now it wants `encoding="utf-8"` in one more place:
```
...
www.photopea.com/code/pp/pp1734993675.js: 2.40MB [00:01, 2.27MB/s]
Traceback (most recent call last):
  File "D:\Downloads\photopea-v2\Updater.py", line 176, in <module>
    find_and_replace(PP,'"\'$!|"))','"\'$!|"))||true')
  File "D:\Downloads\photopea-v2\Updater.py", line 173, in find_and_replace
    pp.write(file1)
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19011-19018: character maps to <undefined>
```
here `with open(os.path.join(root,file),'w') as pp:`

**Comment by DUOLabs333** [comment]
Force-pushed an update that should fix the problem.

**Comment by SCP002** [comment]
It is working now :)
